### ISSUE TITLE
Provide custom registration of custom checks

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl.Plugin.Nsb6.CustomChecks#10] opened 2016-02-17 01:13 UTC
Copied from https://github.com/Particular/ServiceControl/issues/371

**Comment by johnsimons** [comment] 2016-02-17 01:14
@danielmarbach maybe u can look at this user request

**Comment by danielmarbach** [comment] 2016-03-10 16:12
@Particular/servicecontrol-maintainers Unsure about this. The problem is this request is how do we differentiate between auto-registered checks and non-autoregistered steps. Just looking at the constructor doesn't work since the checks are resolved on the container and users could be relying on dependency injection via the container. 

In order to solve this properly we would either need to disable auto registration completely or exclude the custom registered checks from the build up logic. 

There is a workaround:

```
abstract class FtpStorageDirectoryCheck : PeriodicCheck
{
    // constructor with parameter
    protected FtpStorageDirectoryCheck(string path) 
        : base("FTP storage directory check", "FTP Server", TimeSpan.FromSeconds(5))
    {
        _path = path;
    }

    public override CheckResult PerformCheck()
    {
        if (!Directory.Exists(_path))
        {
            return CheckResult.Failed(string.Format("FTP storage directory '{0}' does not exist", _path));                
        }
        return CheckResult.Pass;
    }
}

Ftp1DirectoryChecker : FtpStorageDirectoryCheck 
{
    FtpStorageDirectoryCheck() : base("C:\Path1")
}

Ftp2DirectoryChecker : FtpStorageDirectoryCheck 
{
    FtpStorageDirectoryCheck() : base("C:\Path2")
}
```

No beautiful but would solve the issue the user requesting this currently faces.

Thoughts how to proceed?

**Comment by mikeminutillo** [comment] 2016-03-11 01:53
I don't mind that as a reasonable workaround. Another option I thought of was to create a `DelegateCustomCheck` and eliminate that from the type-scanning somehow. Then provide something like:

``` CSharp
config.Monitoring.CustomCheck("FTP1 check", "FTP Server", TimeSpan.FromSeconds(5), check => return check.Passed);
```

**Comment by danielmarbach** [comment] 2016-03-11 09:20
@Particular/servicecontrol-maintainers I vote for closing as `Won't fix`. Value is as it stand currently not high enough.

**Closed as completed** 2016-10-24 03:54 UTC
Labels: Withdrawn: Won't Fix
